service: study-manager-server
runtime: java8
env: flex
instance_class: F1

# set 2 min instances
manual_scaling:
  instances: 2

# get size from env var, try this without mx, ms
entrypoint: java -Dconfig.file=vault.conf DSMServer.jar
