service: study-manager-backend
runtime: java11
instance_class: B4

manual_scaling:
  instances: 1

network:
  instance_tag: study-manager

entrypoint: java -javaagent:tcell/tcellagent.jar -Xms820m -Xmx820m -Dlog4j.configurationFile=log4j.xml -jar DSMServer.jar

env_variables:
  TCELL_AGENT_HOST_IDENTIFIER: study-manager
  TCELL_AGENT_CACHE_DIR: /tmp
